/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("user").del();
  await knex("user").insert([
    {
      id: 1,
      email: "email@gmail.com",
      name: "alfahmi",
      password: "$2b$10$CaMJc5PQcWluVZ80d9569.readztdZ9ccxs9Ipcrg4BL2GXJ8kgZ2",
      exp: 300,
      gold: 3000,
    },
  ]);

  await knex("kelas").del();
  await knex("kelas").insert([
    { id: 1, name: "kelas1" },
    { id: 2, name: "kelas2" },
  ]);

  await knex("mode_pembelajaran").del();
  await knex("mode_pembelajaran").insert([
    { id: 1, name: "mode pembelajaran 1", kelas_id: 1 },
    { id: 2, name: "mode pembelajaran 2", kelas_id: 1 },
    { id: 3, name: "mode pembelajaran 3", kelas_id: 2 },
    { id: 4, name: "mode pembelajaran 4", kelas_id: 2 },
  ]);

  await knex("mata_pelajaran").del();
  await knex("mata_pelajaran").insert([
    { id: 1, name: "mata pelajaran 1", mode_pembelajaran_id: 1 },
    { id: 2, name: "mata pelajaran 2", mode_pembelajaran_id: 1 },
    { id: 3, name: "mata pelajaran 3", mode_pembelajaran_id: 2 },
    { id: 4, name: "mata pelajaran 4", mode_pembelajaran_id: 2 },
    { id: 5, name: "mata pelajaran 5", mode_pembelajaran_id: 3 },
    { id: 6, name: "mata pelajaran 6", mode_pembelajaran_id: 3 },
    { id: 7, name: "mata pelajaran 7", mode_pembelajaran_id: 4 },
    { id: 8, name: "mata pelajaran 8", mode_pembelajaran_id: 4 },
  ]);

  await knex("bab").del();
  await knex("bab").insert([
    { id: 1, name: "bab 1", mata_pelajaran_id: 1 },
    { id: 2, name: "bab 2", mata_pelajaran_id: 1 },
    { id: 3, name: "bab 1", mata_pelajaran_id: 2 },
    { id: 4, name: "bab 2", mata_pelajaran_id: 2 },
    { id: 5, name: "bab 1", mata_pelajaran_id: 3 },
    { id: 6, name: "bab 2", mata_pelajaran_id: 3 },
    { id: 7, name: "bab 1", mata_pelajaran_id: 4 },
    { id: 8, name: "bab 2", mata_pelajaran_id: 4 },
    { id: 9, name: "bab 1", mata_pelajaran_id: 5 },
    { id: 10, name: "bab 2", mata_pelajaran_id: 5 },
    { id: 11, name: "bab 1", mata_pelajaran_id: 6 },
    { id: 12, name: "bab 2", mata_pelajaran_id: 6 },
    { id: 13, name: "bab 1", mata_pelajaran_id: 7 },
    { id: 14, name: "bab 2", mata_pelajaran_id: 7 },
    { id: 15, name: "bab 1", mata_pelajaran_id: 8 },
    { id: 16, name: "bab 2", mata_pelajaran_id: 8 },
  ]);

  await knex("sub_bab").del();
  await knex("sub_bab").insert([
    { id: 1, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 2, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 3, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 4, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 5, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 6, name: "sub_bab 3", bab_id: 2, isGratis: false },
    { id: 7, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 8, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 9, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 10, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 11, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 12, name: "sub_bab 3", bab_id: 2, isGratis: false },
    { id: 13, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 14, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 15, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 16, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 17, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 18, name: "sub_bab 3", bab_id: 2, isGratis: false },
    { id: 19, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 20, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 21, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 22, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 23, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 24, name: "sub_bab 3", bab_id: 2, isGratis: false },
    { id: 25, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 26, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 27, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 28, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 29, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 30, name: "sub_bab 3", bab_id: 2, isGratis: false },
    { id: 31, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 32, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 33, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 34, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 35, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 36, name: "sub_bab 3", bab_id: 2, isGratis: false },
    { id: 37, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 38, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 39, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 40, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 41, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 42, name: "sub_bab 3", bab_id: 2, isGratis: false },
    { id: 44, name: "sub_bab 1", bab_id: 1, isGratis: true },
    { id: 43, name: "sub_bab 2", bab_id: 1, isGratis: true },
    { id: 45, name: "sub_bab 3", bab_id: 1, isGratis: false },
    { id: 46, name: "sub_bab 1", bab_id: 2, isGratis: true },
    { id: 47, name: "sub_bab 2", bab_id: 2, isGratis: true },
    { id: 48, name: "sub_bab 3", bab_id: 2, isGratis: false },
  ]);

  await knex("jenis_material").del();
  await knex("jenis_material").insert([
    { id: 1, name: "single quiz", exp: 20, gold: 200 },
    { id: 4, name: "end quiz", exp: 40, gold: 400 },
    { id: 2, name: "video", exp: 80, gold: 800 },
    { id: 3, name: "summary", exp: 160, gold: 1600 },
  ]);

  await knex("material").del();
  await knex("material").insert([
    { id: 1, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 2, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 3, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 4, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 5, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 6, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 7, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 8, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 9, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 10, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 11, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 12, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 13, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 14, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 15, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 16, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 17, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 18, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 19, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 20, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 21, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 22, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 23, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 24, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 25, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 26, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 27, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 28, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 29, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 30, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 31, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 32, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 33, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 34, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 35, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 36, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 37, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 38, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 39, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 40, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 41, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 42, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 43, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 44, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 45, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 46, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 47, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 48, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 49, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 50, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 51, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 52, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 53, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 54, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 55, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 56, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 57, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 58, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 59, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 60, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 61, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 62, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 63, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 64, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 65, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 66, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 67, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 68, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 69, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 70, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 71, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 72, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 73, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 74, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 75, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 76, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 77, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 78, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 79, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 80, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 81, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 82, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 83, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 84, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 85, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 86, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 87, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 88, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 89, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 90, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 91, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 92, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 93, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 94, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 95, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 96, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 97, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 98, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 99, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 100, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 101, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 102, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 103, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 104, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 105, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 106, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 107, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 108, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 109, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 110, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 111, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 112, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 113, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 114, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 115, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 116, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 117, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 118, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 119, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 120, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 121, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 122, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 123, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 124, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 125, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 126, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 127, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 128, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 129, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 130, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 131, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 132, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 133, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 134, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 135, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 136, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 137, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 138, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 139, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 140, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 141, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 142, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 143, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 144, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 145, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 146, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 147, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 148, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 149, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 150, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 151, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 152, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 153, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 154, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 155, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 156, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 157, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 158, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 159, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 160, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 161, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 162, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 163, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 164, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 165, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 166, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 167, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 168, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 169, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 170, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 171, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 172, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 173, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 174, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 175, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 176, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
    { id: 177, name: "material 1", sub_bab_id: 1, jenis_material_id: 1 },
    { id: 178, name: "material 2", sub_bab_id: 1, jenis_material_id: 2 },
    { id: 179, name: "material 3", sub_bab_id: 1, jenis_material_id: 3 },
    { id: 180, name: "material 4", sub_bab_id: 1, jenis_material_id: 4 },
    { id: 181, name: "material 1", sub_bab_id: 2, jenis_material_id: 1 },
    { id: 182, name: "material 2", sub_bab_id: 2, jenis_material_id: 2 },
    { id: 183, name: "material 3", sub_bab_id: 2, jenis_material_id: 3 },
    { id: 184, name: "material 4", sub_bab_id: 2, jenis_material_id: 4 },
    { id: 185, name: "material 1", sub_bab_id: 3, jenis_material_id: 1 },
    { id: 186, name: "material 2", sub_bab_id: 3, jenis_material_id: 2 },
    { id: 187, name: "material 3", sub_bab_id: 3, jenis_material_id: 3 },
    { id: 188, name: "material 4", sub_bab_id: 3, jenis_material_id: 4 },
    { id: 189, name: "material 1", sub_bab_id: 4, jenis_material_id: 1 },
    { id: 190, name: "material 2", sub_bab_id: 4, jenis_material_id: 2 },
    { id: 191, name: "material 3", sub_bab_id: 4, jenis_material_id: 3 },
    { id: 192, name: "material 4", sub_bab_id: 4, jenis_material_id: 4 },
  ]);

  await knex("progress_bab").del();
  await knex("progress_bab").insert([
    { id: 1, user_id: 1, bab_id: 1, progress: 50 },
    { id: 2, user_id: 1, bab_id: 2, progress: 0 },
  ]);

  await knex("progress_sub_bab").del();
  await knex("progress_sub_bab").insert([
    { id: 1, user_id: 1, sub_bab_id: 1, progress: 100 },
    { id: 2, user_id: 1, sub_bab_id: 2, progress: 0 },
    { id: 3, user_id: 1, sub_bab_id: 3, progress: 0 },
    { id: 4, user_id: 1, sub_bab_id: 4, progress: 0 },
    { id: 5, user_id: 1, sub_bab_id: 5, progress: 0 },
    { id: 6, user_id: 1, sub_bab_id: 6, progress: 0 },
  ]);

  await knex("progress_material").del();
  await knex("progress_material").insert([
    { id: 1, user_id: 1, material_id: 1, isSelesai: true },
    { id: 2, user_id: 1, material_id: 2, isSelesai: true },
    { id: 3, user_id: 1, material_id: 3, isSelesai: true },
    { id: 4, user_id: 1, material_id: 4, isSelesai: true },
    { id: 5, user_id: 1, material_id: 5, isSelesai: false },
    { id: 6, user_id: 1, material_id: 6, isSelesai: false },
    { id: 7, user_id: 1, material_id: 7, isSelesai: false },
    { id: 8, user_id: 1, material_id: 8, isSelesai: false },
    { id: 9, user_id: 1, material_id: 9, isSelesai: false },
    { id: 10, user_id: 1, material_id: 10, isSelesai: false },
    { id: 11, user_id: 1, material_id: 11, isSelesai: false },
    { id: 12, user_id: 1, material_id: 12, isSelesai: false },
    { id: 13, user_id: 1, material_id: 13, isSelesai: false },
    { id: 14, user_id: 1, material_id: 14, isSelesai: false },
    { id: 15, user_id: 1, material_id: 15, isSelesai: false },
    { id: 16, user_id: 1, material_id: 16, isSelesai: false },
  ]);
};
